"""rename address

Revision ID: 049e8d8b5999
Revises: ad8ea84b294e
Create Date: 2024-07-01 09:31:10.772860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049e8d8b5999'
down_revision = 'ad8ea84b294e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###